"""
routes/insights.py — Endpoints for all Phase 2 agent analysis outputs.

Endpoints
---------
GET /api/insights/themes    — Theme clusters from Agent 4
GET /api/insights/segments  — User segments from Agent 5
GET /api/insights/insights  — Product insights from Agent 6
GET /api/insights/report    — Executive report from Agent 7 (JSON + markdown)
GET /api/insights/latest    — Aggregated snapshot across all outputs
"""

from fastapi import APIRouter, HTTPException, Query
from typing import List, Optional
from collections import Counter

from data_loader import loader
from api_models.response import (
    ThemeResponse,
    SegmentResponse,
    InsightResponse,
    ReportResponse,
    LatestAnalysisResponse,
    SentimentDistribution,
)

router = APIRouter(prefix="/insights", tags=["Insights"])


# ── GET /themes ───────────────────────────────────────────────────────────────

@router.get("/themes", response_model=List[ThemeResponse], summary="Get Theme Clusters")
def get_themes():
    """
    Returns all theme clusters generated by Agent 4 (Theme Clustering).

    Each theme includes a title, description, representative review excerpts,
    and an optional sentiment distribution across member reviews.
    Returns an empty list if the pipeline has not run yet.
    """
    themes = loader.load_themes()
    if not themes:
        return []
    result = []
    for i, t in enumerate(themes):
        result.append(ThemeResponse(
            theme_id=t.get("theme_id") or t.get("id") or str(i + 1),
            title=t.get("title") or t.get("theme") or t.get("name"),
            description=t.get("description") or t.get("summary"),
            review_count=t.get("review_count") or len(t.get("reviews", [])) or len(t.get("representative_reviews", [])),
            representative_reviews=t.get("representative_reviews") or t.get("reviews", []),
            sentiment_distribution=t.get("sentiment_distribution"),
        ))
    return result


# ── GET /segments ─────────────────────────────────────────────────────────────

@router.get("/segments", response_model=List[SegmentResponse], summary="Get User Segments")
def get_segments():
    """
    Returns all user segments generated by Agent 5 (User Segmentation).

    Each segment includes a label, behavioral traits, music discovery challenges,
    and the count of reviews attributed to it.
    Returns an empty list if the pipeline has not run yet.
    """
    segments = loader.load_segments()
    if not segments:
        return []
    result = []
    for i, s in enumerate(segments):
        result.append(SegmentResponse(
            segment_id=s.get("segment_id") or s.get("id") or str(i + 1),
            label=s.get("label") or s.get("segment_type") or s.get("name"),
            traits=s.get("traits") or s.get("characteristics", []),
            challenges=s.get("challenges") or s.get("pain_points", []),
            review_count=s.get("review_count") or len(s.get("reviews", [])),
            listening_behaviors=s.get("listening_behaviors") or s.get("behaviors", []),
        ))
    return result


# ── GET /insights ─────────────────────────────────────────────────────────────

@router.get("/insights", response_model=List[InsightResponse], summary="Get Product Insights")
def get_insights():
    """
    Returns product insights generated by Agent 6 (Product Insight Generator).

    Each insight describes an improvement opportunity, its target user segment,
    an impact score (0–1), top feature requests, and pain points addressed.
    Returns an empty list if the pipeline has not run yet.
    """
    insights = loader.load_insights()
    if not insights:
        return []
    result = []
    for i, ins in enumerate(insights):
        result.append(InsightResponse(
            insight_id=ins.get("insight_id") or ins.get("id") or str(i + 1),
            opportunity=ins.get("opportunity") or ins.get("title") or ins.get("feature"),
            target_segment=ins.get("target_segment") or ins.get("segment"),
            impact_score=ins.get("impact_score") or ins.get("score"),
            feature_requests=ins.get("feature_requests") or ins.get("requests", []),
            pain_points=ins.get("pain_points") or ins.get("barriers", []),
        ))
    return result


# ── GET /report ───────────────────────────────────────────────────────────────

@router.get("/report", response_model=ReportResponse, summary="Get Executive Report")
def get_executive_report():
    """
    Returns the latest executive report produced by Agent 7.

    Includes both the structured JSON payload and the full markdown report text.
    Returns `available: false` with null fields if the pipeline has not run yet.
    """
    report_json = loader.load_report_json()
    report_md   = loader.load_report_markdown()

    if report_json is None and report_md is None:
        return ReportResponse(available=False)

    return ReportResponse(
        available=True,
        generated_at=report_json.get("generated_at") if report_json else None,
        summary=report_json.get("summary") if report_json else None,
        markdown_report=report_md,
        json_report=report_json,
    )


# ── GET /latest ───────────────────────────────────────────────────────────────

@router.get("/latest", response_model=LatestAnalysisResponse, summary="Get Latest Analysis Snapshot")
def get_latest_analysis():
    """
    Returns an aggregated snapshot of the most recent pipeline run's results.

    Includes:
    - Total review / theme / segment counts
    - Sentiment distribution across all analyzed reviews
    - Top theme and top segment labels
    - Whether an executive report is available
    """
    reviews  = loader.load_analyzed_reviews()
    themes   = loader.load_themes()
    segments = loader.load_segments()

    if not reviews and not themes and not segments:
        return LatestAnalysisResponse(data_available=False, report_available=loader.report_available())

    # Sentiment distribution
    sentiments = [r.get("sentiment", "").lower() for r in reviews if r.get("sentiment")]
    counts = Counter(sentiments)
    sentiment_dist = SentimentDistribution(
        positive=counts.get("positive", 0),
        neutral=counts.get("neutral", 0),
        negative=counts.get("negative", 0),
    )

    # Top theme — most reviews
    top_theme: Optional[str] = None
    if themes:
        best = max(
            themes,
            key=lambda t: t.get("review_count") or len(t.get("reviews", [])) or len(t.get("representative_reviews", [])),
            default=None,
        )
        if best:
            top_theme = best.get("title") or best.get("theme") or best.get("name")

    # Top segment — most reviews
    top_segment: Optional[str] = None
    if segments:
        best_seg = max(
            segments,
            key=lambda s: s.get("review_count") or len(s.get("reviews", [])),
            default=None,
        )
        if best_seg:
            top_segment = best_seg.get("label") or best_seg.get("segment_type") or best_seg.get("name")

    return LatestAnalysisResponse(
        data_available=True,
        total_reviews=len(reviews),
        total_themes=len(themes),
        total_segments=len(segments),
        sentiment_distribution=sentiment_dist,
        top_theme=top_theme,
        top_segment=top_segment,
        report_available=loader.report_available(),
    )
