'use client';

import { useState, useEffect } from 'react';
import { FileText, Download, Calendar } from 'lucide-react';
import { getReport } from '@/lib/api';
import type { Report } from '@/lib/types';
import ErrorAlert from '@/components/ErrorAlert';

export default function ExecutiveSummaryPage() {
  const [report, setReport] = useState<Report | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchData() {
      try {
        const data = await getReport();
        setReport(data);
      } catch (err) {
        setError('Failed to fetch executive report');
        console.error(err);
      } finally {
        setLoading(false);
      }
    }
    fetchData();
  }, []);

  return (
    <div className="space-y-8 animate-fade-in">
      {/* Error Alert */}
      {error && (
        <ErrorAlert 
          message={error}
        />
      )}

      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold mb-2 flex items-center gap-3">
            <FileText className="text-indigo-500" />
            Executive Summary
          </h1>
          <p className="text-slate-400 dark:text-slate-400">
            Comprehensive analysis report generated by AI agents
          </p>
        </div>
        {report && (
          <button className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 px-4 py-2 rounded-lg font-medium transition-colors">
            <Download size={16} />
            Export Report
          </button>
        )}
      </div>

      {/* Report Content */}
      {report ? (
        <div className="space-y-6">
          {/* Report Metadata */}
          <div className="card">
            <div className="flex items-center gap-4 text-sm text-slate-400 dark:text-slate-400">
              <div className="flex items-center gap-2">
                <Calendar size={16} />
                <span>
                  Generated: {report.generated_at ? new Date(report.generated_at).toLocaleDateString() : 'N/A'}
                </span>
              </div>
            </div>
          </div>

          {/* Summary */}
          {report.summary && (
            <div className="card">
              <h2 className="text-xl font-semibold mb-4 text-indigo-400">Executive Summary</h2>
              <p className="text-slate-300 dark:text-slate-300 leading-relaxed">{report.summary}</p>
            </div>
          )}

          {/* Markdown Report */}
          {report.content && (
            <div className="card">
              <h2 className="text-xl font-semibold mb-4 text-indigo-400">Full Report</h2>
              <div className="prose prose-invert max-w-none">
                <div className="whitespace-pre-wrap text-slate-300 dark:text-slate-300 leading-relaxed">
                  {report.content}
                </div>
              </div>
            </div>
          )}

          {/* Insights */}
          {report.insights && report.insights.length > 0 && (
            <div className="card">
              <h2 className="text-xl font-semibold mb-4 text-indigo-400">Key Insights</h2>
              <div className="space-y-3">
                {report.insights.map((insight) => (
                  <div key={insight.id} className="p-4 bg-gray-100 dark:bg-slate-800 rounded-lg">
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-xs font-medium text-indigo-400 uppercase">
                        {insight.type}
                      </span>
                      <span className="text-xs text-slate-400">
                        {(insight.confidence * 100).toFixed(0)}% confidence
                      </span>
                    </div>
                    <p className="text-sm text-gray-700 dark:text-slate-300">{insight.content}</p>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      ) : (
        <div className="card text-center py-12">
          <FileText size={48} className="text-slate-600 mx-auto mb-4" />
          <p className="text-slate-400 dark:text-slate-400 mb-4">
            No executive report available yet.
          </p>
          <p className="text-slate-500 dark:text-slate-500 text-sm">
            Run the pipeline to generate the comprehensive analysis report.
          </p>
        </div>
      )}
    </div>
  );
}
